### ISSUE TITLE
Mobs added by Thaumcraft have no aspects set

### ISSUE THREAD

**Issue by IcarussOne** [TheCodex6824/ThaumcraftFix#15]
This ones pretty major (at least to me), none of the mobs added by Thaumcraft have any aspects set on them for some reason and it affects content like the crystal drops obtained from liquid death. Maybe base off their set aspects from 5 to fix that?

Vanilla mobs have aspects as normal.

**Comment by TechnoMysterio** [comment]
Well going over the source code it looks like the game is trying to register aspects for Thaumcraft entities (common/config/ConfigAspects), even for things like Flux Rifts, but I guess it's not working for some reason. Still, does make choosing aspects easier.

**Comment by TheCodex6824** [comment]
The registration done by Thaumcraft wasn't working because the registrations were done in the form of `Thaumcraft.<name>`, but the entities were actually just registered as `<name>`. This isn't referring to the registry name, it's a separate name (although registry name would probably have been a better choice - I'm guessing this was ported from a version where registry names didn't exist).
