### ISSUE TITLE
Aspect description

### ISSUE THREAD

**Issue by xJon** [TheCodex6824/ThaumcraftFix#36]
Certain addons add back aspects from Thaumcraft 4, and a couple of them lack a description:
![image](https://github.com/user-attachments/assets/d265d7b8-d38d-4d4c-8862-0c459d273a0b)
![image](https://github.com/user-attachments/assets/1dbb0ab3-a03b-4319-819d-07844f4e7812)

Oddly enough I wasn't easily able to pinpoint which addon does this, and I'm not sure where would be the best place to add the description. I thought about potentially overriding Thaumcraft's language file?

Would appreciate any advice, thanks!

**Comment by TheCodex6824** [comment]
The aspect description is a base Thaumcraft feature - every aspect has a description with a lang key of `tc.aspect.<tag>`. Due to how language keys work, you can add them anywhere as long as the resource loader can find them - it doesn't have to be in Thaumcraft's lang file itself. Ideally the addons would add it in their lang file, but you can also make your own.

**Comment by xJon** [comment]
Thank you :)
